# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/chainguard-migration-demo:ref:refs/heads/main

permissions:
  contents: write
  pull_requests: write
