architecture: standalone
global:
  redis:
    password: "redis"
replica:
  replicaCount: 1
master:
  kind: Deployment
image:
  registry: cgr.dev
  repository: cgr-demo.com/redis-server-bitnami
  tag: 8.0.2-r2-202506190808
